DERBY-398 enable tests for J2ME Attaching a patch 'parameterMapping.diff' which changes the tests jdbcapi/parameterMapping.java and lang/updatableResultSet.java to run in J2ME/CDC/FP. Changes are:
* In parameterMapping.java, SQL types DECIMAL and NUMERIC are mapped to the String class in B3_GET_OBJECT for J2ME.
* When changing the tests, I have covered testing of SQL DECIMAL type. This is tested using wrapper methods in BigDecimalHandler which use get/setString methods for J2ME. I have not used the wrapper in cases where DECIMAL type is already being tested with get/set/updateXXX methods of other JDBC types.
* The tests work the same way as before in non-J2ME environments.
* In JSR169, get/setUnicodeStream methods are not present. NoSuchMethodError exception is used to handle these cases.
* New masters are needed for the tests. These are to account for absence of BigDecimal class in J2ME and methods which are not present in JSR169.

Ran both the changed tests using Sun JDK1.4.2 (all frameworks) and IBM WCTME 5.7 j9_foundation. 



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@372708 13f79535-47bb-0310-9956-ffa450edef68