DERBY-398  add jdk14 suite to J2ME
Contributed by Deepa Remesh
 Attaching a patch 'jdk14_tests.diff' which adds jdk14 suite and some more tests to run with J2ME/CDC/FP. Changes are:

M java\tools\org\apache\derby\impl\tools\ij\mtTestCase.java

If ij.dataSource property is specified, remove ij.database and ij.protocol property. Similar to what is done by test harness. This is needed for stress.multi.

M java\testing\org\apache\derbyTesting\functionTests\tests\i18n\iepnegativetests_ES_app.properties
M java\testing\org\apache\derbyTesting\functionTests\multi\stress\init.properties
M java\testing\org\apache\derbyTesting\functionTests\multi\stress\run.properties

Change 'database' property to 'ij.database' and add ij.dataSource properties.

M java\testing\org\apache\derbyTesting\functionTests\tests\lang\holdCursorJava.java
M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\autoGeneratedJdbc30.java

Execute procedure tests only if DriverManager class is present.

A java\testing\org\apache\derbyTesting\functionTests\tests\lang\procedureJdbc30_app.properties
A java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\checkDataSource30_app.properties
M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\copyfiles.ant
M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\parameterMetaDataJdbc30_app.properties

These tests are part of jdk14 suite but cannot be run with JSR169.

M java\testing\org\apache\derbyTesting\functionTests\tests\lang\maxMemPerTab_app.properties
M java\testing\org\apache\derbyTesting\functionTests\tests\lang\triggerStream_app.properties
M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\LOBTest_app.properties
M java\testing\org\apache\derbyTesting\functionTests\tests\store\bootLock_app.properties

Removed 'runwithfoundation=false' exclude from these tests

M java\testing\org\apache\derbyTesting\functionTests\tests\lang\copyfiles.ant
D java\testing\org\apache\derbyTesting\functionTests\tests\lang\maxMemPerTab.sql
A java\testing\org\apache\derbyTesting\functionTests\tests\lang\triggerStream.java
A java\testing\org\apache\derbyTesting\functionTests\tests\lang\maxMemPerTab.java
D java\testing\org\apache\derbyTesting\functionTests\tests\lang\triggerStream.sql
M java\testing\org\apache\derbyTesting\functionTests\suites\derbylang.runall
M java\testing\org\apache\derbyTesting\functionTests\master\maxMemPerTab.out
M java\testing\org\apache\derbyTesting\functionTests\master\triggerStream.out
M java\testing\org\apache\derbyTesting\functionTests\util\StreamUtil.java
M java\testing\org\apache\derbyTesting\functionTests\util\ProcedureTest.java

maxMemPerTab and triggerStream tests are converted from sql to java to avoid using procedures with nested connections.

M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\dbMetaDataJdbc30.java
M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\resultsetJdbc30.java

NoSuchMethodError for methods not present in JSR169.

M java\testing\org\apache\derbyTesting\functionTests\tests\jdbcapi\users_app.properties

User and password are specified in databaseName itself so that they don't get re-used for other connections in the test

M java\testing\org\apache\derbyTesting\functionTests\tests\store\bootLock1.java
M java\testing\org\apache\derbyTesting\functionTests\tests\store\bootLock.java

Use Datasource instead of DriverManager

M java\testing\org\apache\derbyTesting\functionTests\harness\RunList.java
M java\testing\org\apache\derbyTesting\functionTests\suites\jdk14.properties

Change 'jdk14test' property to 'jdbc30test' property. Add check for jdb30test so that it can run with foundation vm.

M java\testing\org\apache\derbyTesting\functionTests\master\resultsetJdbc30.out

Small correction in the test and master.

A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\iepnegativetests_ES.out

Added new master because of difference in output of show connections.

A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\dbMetaDataJdbc30.out
A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\LOBTest.out
A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\autoGeneratedJdbc30.out
A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\resultsetJdbc30.out
A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\holdCursorJava.out
A java\testing\org\apache\derbyTesting\functionTests\master\j9_foundation\users.out

New masters for difference in behaviour in J2ME

M java\testing\org\apache\derbyTesting\functionTests\suites\jdk14.runall

Remove store/bootlock.java which is also part of store suite.




git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@370059 13f79535-47bb-0310-9956-ffa450edef68