DERBY-4860 RunSuite on derbylang and other subsuites fails with java.lang.NoClassDefFoundError because of prepended ^
git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@1025795 13f79535-47bb-0310-9956-ffa450edef68