DERBY-3561: testStartStopManagementFromApplication fails with "expected:<2> but was:<5>"  - applying same change to ServerPropertiesTest.policy's section for classes as    revision 644248 did to its section for derby.jar.  - that is, added permission which allows ServerPropertiesTest's JVM to unregister    MBeans that are automatically registered upon Derby boot by that test or previous    tests.
git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@689460 13f79535-47bb-0310-9956-ffa450edef68