DERBY-3519: junit regression test failure in testInertTime(org.apache.derbyTesting.functionTests.tests.lang.TimeHandlingTest)junit.framework.AssertionFailedError: expected:<2> but was:<3>
git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@1464386 13f79535-47bb-0310-9956-ffa450edef68