DERBY-3773 ImportExportLobTest failed on Zos Clobs differ at index 1 expected:<99> but was:<196>
Needed to specify codeset when importing file.



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@676001 13f79535-47bb-0310-9956-ffa450edef68