DERBY-3548: NoClassDefFoundError failure in SystemPrivilegesPermissionTest for weme6.1
Merged to 10.4 with svn merge -r 639058:639059 ../derby-scratch
No conflicts.


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.4@647474 13f79535-47bb-0310-9956-ffa450edef68