DERBY-3519 junit regression test failure in testInertTime(org.apache.derbyTesting.functionTests.tests.lang.TimeHandlingTest)junit.framework.AssertionFailedError: expected:<2> but was:<3>
merge from trunk revision  1464386.  Contributed by Knut Anders Hatlen



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.10@1493156 13f79535-47bb-0310-9956-ffa450edef68