DERBY-3919 Changing derby versions can cause java.lang.NoSuchMethodError on DatabaseMetaData call
Bump maintenance version so SPS plans will get cleared.



git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.1@707205 13f79535-47bb-0310-9956-ffa450edef68