DERBY-2770: testBlobAfterCommit(....jdbcapi.BlobClob4BlobTest) fails with 'Unexpected SQL state. expected:<XJ[073]> but was:<XJ[215]>'
Changed error message to reflect that XJ215 is used both after free()
has been called on a Lob and after the lob's transaction has been
committed.

Changed SQL state when locators are invalid from XJ073 to XJ215 on the
client driver.

Patch contributed by Øystein Grøvlen.


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@545910 13f79535-47bb-0310-9956-ffa450edef68