DERBY-683: Commit _tstpatch3_ by Myrna. Adds derbyTesting.encoding property to harness. Excludes encodingTests from all JDKs except Sun JDK 1.5. Further investigation is required to understand why this is necessary. The changes introduced in this patch (specifically, setting -Dfile.encoding on the command- line of the spawned JVM) should not cause NoClassDefFoundErrors on JDK 1.4.2, but they do.
Committed for Deepa Remesh <dremesh@gmail.com> and 
Myrna Van Lunteren <m.v.lunteren@gmail.com>


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@379723 13f79535-47bb-0310-9956-ffa450edef68