DERBY-1444 Using -Djvmflags option causes NoClassDefFoundError. Contributed by Vemund.Ostgaard@sun.com
git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@417206 13f79535-47bb-0310-9956-ffa450edef68