DERBY-5468: Assertion failed in AutomaticIndexStatisticsMultiTest.testMTSelectWithDDL (expected:<0> but was:<1>)
Improves the error reporting such that the cause of the error is reported.

Patch file: derby-5468-1a-error_reporting.diff


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@1185187 13f79535-47bb-0310-9956-ffa450edef68