DERBY-1444: Using -Djvmflags option causes NoClassDefFoundError
Merge fix by Vemund Ostgaard to 10.1 branch. Original fix committed as revision
417206. 


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/branches/10.1@417268 13f79535-47bb-0310-9956-ffa450edef68