DERBY-3561: testStartStopManagementFromApplication(org.apache.derbyTesting.functionTests.tests.management.ManagementMBeanTest)junit.framework.AssertionFailedError: expected:<2> but was:<5>
Added permission so that all tests can unregister MBeans when they
shut down the database.

Patch contributed by John H. Embretsen <John.Embretsen@Sun.COM>.


git-svn-id: https://svn.apache.org/repos/asf/db/derby/code/trunk@644248 13f79535-47bb-0310-9956-ffa450edef68